import { Icon } from "./types";

export const ext: Icon[] = [
  {
    icon: "adobe_ae",
    filenames: ["aep"],
  },
  {
    icon: "adobe_ai",
    filenames: ["ai"],
  },
  {
    icon: "adobe_id",
    filenames: ["indd", "indl", "indb"],
  },
  {
    icon: "image",
    filenames: [
      "psd",
      "psb",
      "png",
      "jpeg",
      "jpg",
      "gif",
      "ico",
      "tif",
      "tiff",
      "ami",
      "apx",
      "avif",
      "bmp",
      "bpg",
      "brk",
      "cur",
      "dds",
      "dng",
      "exr",
      "fpx",
      "gbr",
      "img",
      "jbig2",
      "jb2",
      "jng",
      "jxr",
      "pgf",
      "pic",
      "raw",
      "webp",
      "eps",
      "afphoto",
      "ase",
      "aseprite",
      "clip",
      "cpt",
      "heif",
      "heic",
      "kra",
      "mdp",
      "ora",
      "pdn",
      "reb",
      "sai",
      "tga",
      "xcf",
      "jfif",
      "ppm",
      "pbm",
      "pgm",
      "pnm",
      "icns",
    ],
  },
  {
    icon: "adobe_xd",
    filenames: ["xd"],
  },
  {
    icon: "amber",
    filenames: ["ab", "amber"],
  },
  {
    icon: "android",
    filenames: ["apk", "smali", "dex"],
  },
  {
    icon: "angular",
    filenames: ["ng-template"],
  },
  {
    icon: "antlr",
    filenames: ["g4"],
  },
  {
    icon: "api_blueprint",
    filenames: ["apib", "apiblueprint"],
  },
  {
    icon: "asciidoc",
    filenames: ["adoc", "asciidoc"],
  },
  {
    icon: "key",
    filenames: ["asc", "pub", "key", "pem", "gpg", "passwd", "keystore"],
  },
  {
    icon: "assembly",
    filenames: [
      "asm",
      "a51",
      "inc",
      "nasm",
      "s",
      "ms",
      "agc",
      "ags",
      "aea",
      "argus",
      "mitigus",
      "binsource",
    ],
  },
  {
    icon: "astro",
    filenames: ["astro"],
  },
  {
    icon: "audio",
    filenames: [
      "aac",
      "aiff",
      "alac",
      "flac",
      "m4a",
      "m4p",
      "mogg",
      "mp3",
      "oga",
      "opus",
      "wav",
      "wma",
      "wv",
    ],
  },
  {
    icon: "azure_pipelines",
    filenames: [
      "azure-pipelines.yml",
      "azure-pipelines.yaml",
      "azure-pipelines-main.yml",
      "azure-pipelines-main.yaml",
    ],
  },
  {
    icon: "bash",
    filenames: ["sh", "ksh", "csh", "tcsh", "zsh", "bash", "awk", "fish"],
  },
  {
    icon: "batch",
    filenames: ["bat", "cmd"],
  },
  {
    icon: "bazel",
    filenames: ["bzl", "bazel"],
  },
  {
    icon: "binary",
    filenames: ["bin"],
  },
  {
    icon: "c",
    filenames: ["c", "i", "mi"],
  },
  {
    icon: "c_header",
    filenames: ["h"],
  },
  {
    icon: "caddy",
    filenames: ["caddyfile"],
  },
  {
    icon: "certificate",
    filenames: ["cer", "cert", "crt", "pfx"],
  },
  {
    icon: "clojure",
    filenames: ["clj", "cljs", "cljc"],
  },
  {
    icon: "cmake",
    filenames: ["cmake"],
  },
  {
    icon: "cobol",
    filenames: ["cob", "cbl"],
  },
  {
    icon: "coffeescript",
    filenames: ["coffee", "cson", "iced"],
  },
  {
    icon: "cpp",
    filenames: ["cc", "cpp", "cxx", "c++", "cp", "mii", "ii"],
  },
  {
    icon: "cpp_header",
    filenames: ["hh", "hpp", "hxx", "h++", "hp", "tcc", "inl"],
  },
  {
    icon: "csharp",
    filenames: ["cs", "csx", "csharp"],
  },
  {
    icon: "css",
    filenames: ["css"],
  },
  {
    icon: "css_map",
    filenames: ["css.map"],
  },
  {
    icon: "csv",
    filenames: ["csv", "tsv", "psv"],
  },
  {
    icon: "cucumber",
    filenames: ["feature", "features"],
  },
  {
    icon: "cuda",
    filenames: ["cu", "cuh"],
  },
  {
    icon: "d",
    filenames: ["d", "di"],
  },
  {
    icon: "dart",
    filenames: ["dart"],
  },
  {
    icon: "dart_generated",
    filenames: ["freezed.dart", "g.dart"],
  },
  {
    icon: "database",
    filenames: [
      "pdb",
      "sql",
      "pks",
      "pkb",
      "accdb",
      "mdb",
      "sqlite",
      "sqlite3",
      "pgsql",
      "postgres",
      "plpgsql",
      "psql",
      "db",
      "db3",
    ],
  },
  {
    icon: "dhall",
    filenames: ["dhall", "dhallb"],
  },
  {
    icon: "django",
    filenames: ["djt"],
  },
  {
    icon: "docker",
    filenames: ["dockerfile", "containerfile"],
  },
  {
    icon: "docker_compose",
    filenames: [
      "docker-compose.yml",
      "docker-compose.yaml",
      "compose.yaml",
      "compose.yml",
    ],
  },
  {
    icon: "docker_ignore",
    filenames: ["dockerignore", "containerignore"],
  },
  {
    icon: "drawio",
    filenames: ["drawio", "dio"],
  },
  {
    icon: "ejs",
    filenames: ["ejs"],
  },
  {
    icon: "elixir",
    filenames: ["ex", "exs", "eex", "leex", "heex"],
  },
  {
    icon: "elm",
    filenames: ["elm"],
  },
  {
    icon: "env",
    filenames: ["env"],
  },
  {
    icon: "erlang",
    filenames: ["erl"],
  },
  {
    icon: "exe",
    filenames: ["exe", "msi"],
  },
  {
    icon: "figma",
    filenames: ["fig"],
  },
  {
    icon: "font",
    filenames: [
      "woff",
      "woff2",
      "ttf",
      "eot",
      "suit",
      "otf",
      "bmap",
      "fnt",
      "odttf",
      "ttc",
      "font",
      "fonts",
      "sui",
      "ntf",
      "mrf",
    ],
  },
  {
    icon: "fortran",
    filenames: ["f", "f77", "f90", "f95", "f03", "f08"],
  },
  {
    icon: "fsharp",
    filenames: ["fs", "fsx", "fsi", "fsproj"],
  },
  {
    icon: "git",
    filenames: ["patch"],
  },
  {
    icon: "gitlab",
    filenames: ["gitlab-ci.yml"],
  },
  {
    icon: "gleam",
    filenames: ["gleam"],
  },
  {
    icon: "go",
    filenames: ["go"],
  },
  {
    icon: "godot",
    filenames: ["gd"],
  },
  {
    icon: "godot_assets",
    filenames: [
      "godot",
      "tres",
      "tscn",
      "gdns",
      "gdnlib",
      "gdshader",
      "gdshaderinc",
      "gdextension",
    ],
  },
  {
    icon: "gradle",
    filenames: ["gradle"],
  },
  {
    icon: "graphql",
    filenames: ["graphql", "gql"],
  },
  {
    icon: "groovy",
    filenames: ["groovy"],
  },
  {
    icon: "haml",
    filenames: ["haml"],
  },
  {
    icon: "handlebars",
    filenames: ["hbs", "mustache"],
  },
  {
    icon: "haskell",
    filenames: ["hs"],
  },
  {
    icon: "haxe",
    filenames: ["hx"],
  },
  {
    icon: "html",
    filenames: ["htm", "html", "xhtml", "html_vm", "asp"],
  },
  {
    icon: "http",
    filenames: ["http", "rest"],
  },
  {
    icon: "huff",
    filenames: ["huff"],
  },
  {
    icon: "java",
    filenames: ["java", "jsp"],
  },
  {
    icon: "java_class",
    filenames: ["class"],
  },
  {
    icon: "java_jar",
    filenames: ["jar"],
  },
  {
    icon: "javascript",
    filenames: ["esx", "js", "cjs", "mjs"],
  },
  {
    icon: "javascript_config",
    filenames: ["jsconfig.json"],
  },
  {
    icon: "javascript_map",
    filenames: ["js.map", "mjs.map", "cjs.map"],
  },
  {
    icon: "javascript_react",
    filenames: ["jsx"],
  },
  {
    icon: "javascript_test",
    filenames: [
      "spec.js",
      "spec.cjs",
      "spec.mjs",
      "e2e-spec.js",
      "e2e-spec.cjs",
      "e2e-spec.mjs",
      "test.js",
      "test.cjs",
      "test.mjs",
      "js.snap",
      "cy.js",
      "spec.jsx",
      "test.jsx",
      "jsx.snap",
      "cy.jsx",
    ],
  },
  {
    icon: "jinja",
    filenames: ["jinja", "jinja2", "j2", "jinja-html"],
  },
  {
    icon: "json",
    filenames: [
      "json",
      "jsonc",
      "tsbuildinfo",
      "json5",
      "jsonl",
      "ndjson",
      "hjson",
      "webmanifest",
    ],
  },
  {
    icon: "json_schema",
    filenames: ["schema.json"],
  },
  {
    icon: "julia",
    filenames: ["jl"],
  },
  {
    icon: "jupyter",
    filenames: ["ipynb"],
  },
  {
    icon: "kotlin",
    filenames: ["kt", "kts"],
  },
  {
    icon: "laravel",
    filenames: ["blade.php", "inky.php"],
  },
  {
    icon: "latex",
    filenames: ["tex", "sty", "dtx", "ltx"],
  },
  {
    icon: "less",
    filenames: ["less"],
  },
  {
    icon: "lib",
    filenames: ["lib", "bib"],
  },
  {
    icon: "liquid",
    filenames: ["liquid"],
  },
  {
    icon: "lisp",
    filenames: ["lisp", "lsp", "cl", "fast"],
  },
  {
    icon: "log",
    filenames: ["log"],
  },
  {
    icon: "lua",
    filenames: ["lua"],
  },
  {
    icon: "luau",
    filenames: ["luau"],
  },
  {
    icon: "makefile",
    filenames: ["mk"],
  },
  {
    icon: "markdown",
    filenames: ["md", "markdown", "rst"],
  },
  {
    icon: "markdown_mdx",
    filenames: ["mdx"],
  },
  {
    icon: "marko",
    filenames: ["marko"],
  },
  {
    icon: "mermaid",
    filenames: ["mmd", "mermaid"],
  },
  {
    icon: "meson",
    filenames: ["wrap"],
  },
  {
    icon: "mjml",
    filenames: ["mjml"],
  },
  {
    icon: "ms_excel",
    filenames: ["xlsx", "xlsm", "xls"],
  },
  {
    icon: "ms_powerpoint",
    filenames: [
      "pptx",
      "ppt",
      "pptm",
      "potx",
      "potm",
      "ppsx",
      "ppsm",
      "pps",
      "ppam",
      "ppa",
      "odp",
    ],
  },
  {
    icon: "ms_word",
    filenames: ["doc", "docx", "rtf", "odt"],
  },
  {
    icon: "nextflow",
    filenames: ["nf"],
  },
  {
    icon: "nginx",
    filenames: ["nginx", "nginxconf", "nginxconfig"],
  },
  {
    icon: "nim",
    filenames: ["nim", "nimble"],
  },
  {
    icon: "ninja",
    filenames: ["ninja"],
  },
  {
    icon: "nix",
    filenames: ["nix"],
  },
  {
    icon: "nuget",
    filenames: ["nupkg"],
  },
  {
    icon: "nunjucks",
    filenames: ["njk", "nunjucks"],
  },
  {
    icon: "ocaml",
    filenames: ["ml", "mli", "cmx"],
  },
  {
    icon: "org",
    filenames: ["org"],
  },
  {
    icon: "pdf",
    filenames: ["pdf"],
  },
  {
    icon: "perl",
    filenames: ["pm", "raku"],
  },
  {
    icon: "php",
    filenames: ["php"],
  },
  {
    icon: "plantuml",
    filenames: ["pu", "puml", "plantuml"],
  },
  {
    icon: "postcss",
    filenames: ["pcss", "sss"],
  },
  {
    icon: "powershell",
    filenames: ["ps1", "psm1", "psd1", "ps1xml", "psc1", "pssc"],
  },
  {
    icon: "prisma",
    filenames: ["prisma"],
  },
  {
    icon: "prolog",
    filenames: ["p", "pro", "pl"],
  },
  {
    icon: "properties",
    filenames: [
      "ini",
      "dlc",
      "config",
      "conf",
      "properties",
      "prop",
      "settings",
      "option",
      "props",
      "prefs",
      "sln.dotsettings",
      "sln.dotsettings.user",
      "cfg",
    ],
  },
  {
    icon: "proto",
    filenames: ["proto"],
  },
  {
    icon: "pug",
    filenames: ["jade", "pug"],
  },
  {
    icon: "python",
    filenames: ["py"],
  },
  {
    icon: "python_compiled",
    filenames: ["pyc", "pyo", "pyd"],
  },
  {
    icon: "r",
    filenames: ["r", "rmd"],
  },
  {
    icon: "racket",
    filenames: ["rkt"],
  },
  {
    icon: "razor",
    filenames: ["cshtml", "vbhtml"],
  },
  {
    icon: "reason",
    filenames: ["re", "rei"],
  },
  {
    icon: "rescript",
    filenames: ["res"],
  },
  {
    icon: "ruby",
    filenames: ["rb", "erb", "rbs"],
  },
  {
    icon: "rust",
    filenames: ["rs", "ron"],
  },
  {
    icon: "salesforce",
    filenames: ["cls"],
  },
  {
    icon: "sass",
    filenames: ["scss", "sass"],
  },
  {
    icon: "scala",
    filenames: ["scala"],
  },
  {
    icon: "super_collider",
    filenames: ["sc", "scd"],
  },
  {
    icon: "search",
    filenames: ["code-search"],
  },
  {
    icon: "shader",
    filenames: [
      "glsl",
      "vert",
      "tesc",
      "tese",
      "geom",
      "frag",
      "comp",
      "vert.glsl",
      "tesc.glsl",
      "tese.glsl",
      "geom.glsl",
      "frag.glsl",
      "comp.glsl",
      "vertex.glsl",
      "geometry.glsl",
      "fragment.glsl",
      "compute.glsl",
      "ts.glsl",
      "gs.glsl",
      "vs.glsl",
      "fs.glsl",
      "shader",
      "vertexshader",
      "fragmentshader",
      "geometryshader",
      "computeshader",
      "hlsl",
      "pixel.hlsl",
      "geometry.hlsl",
      "compute.hlsl",
      "tessellation.hlsl",
      "px.hlsl",
      "geom.hlsl",
      "comp.hlsl",
      "tess.hlsl",
      "wgsl",
    ],
  },
  {
    icon: "sketch",
    filenames: ["sketch"],
  },
  {
    icon: "solidity",
    filenames: ["sol"],
  },
  {
    icon: "spwn",
    filenames: ["spwn"],
  },
  {
    icon: "stata",
    filenames: ["ado", "do", "dta"],
  },
  {
    icon: "storybook",
    filenames: [
      "stories.js",
      "stories.jsx",
      "stories.mdx",
      "story.js",
      "story.jsx",
      "stories.ts",
      "stories.tsx",
      "story.ts",
      "story.tsx",
      "story.mdx",
    ],
  },
  {
    icon: "storybook_svelte",
    filenames: ["story.svelte", "stories.svelte"],
  },
  {
    icon: "storybook_vue",
    filenames: ["story.vue", "stories.vue"],
  },
  {
    icon: "sublime",
    filenames: ["sublime-project", "sublime-workspace"],
  },
  {
    icon: "svelte",
    filenames: ["svelte"],
  },
  {
    icon: "svg",
    filenames: ["svg"],
  },
  {
    icon: "swift",
    filenames: ["swift"],
  },
  {
    icon: "tauri",
    filenames: ["tauri"],
  },
  {
    icon: "terraform",
    filenames: ["tf", "tf.json", "tfvars", "tfstate", "tfbackend"],
  },
  {
    icon: "text",
    filenames: ["txt"],
  },
  {
    icon: "todo",
    filenames: ["todo"],
  },
  {
    icon: "toml",
    filenames: ["toml"],
  },
  {
    icon: "twig",
    filenames: ["twig"],
  },
  {
    icon: "twine",
    filenames: ["tw", "twee"],
  },
  {
    icon: "typescript",
    filenames: ["ts"],
  },
  {
    icon: "typescript_config",
    filenames: ["tsconfig.json"],
  },
  {
    icon: "typescript_def",
    filenames: ["d.ts", "d.cts", "d.mts"],
  },
  {
    icon: "typescript_react",
    filenames: ["tsx"],
  },
  {
    icon: "typescript_test",
    filenames: [
      "spec.ts",
      "spec.cts",
      "spec.mts",
      "cy.ts",
      "e2e-spec.ts",
      "e2e-spec.cts",
      "e2e-spec.mts",
      "test.ts",
      "test.cts",
      "test.mts",
      "ts.snap",
      "spec-d.ts",
      "test-d.ts",
      "spec.tsx",
      "test.tsx",
      "tsx.snap",
      "cy.tsx",
    ],
  },
  {
    icon: "typst",
    filenames: ["typ"],
  },
  {
    icon: "unity",
    filenames: ["unity"],
  },
  {
    icon: "url",
    filenames: ["url"],
  },
  {
    icon: "v",
    filenames: ["v"],
  },
  {
    icon: "vento",
    filenames: ["vto"],
  },
  {
    icon: "verilog",
    filenames: ["vhd", "sv", "svh"],
  },
  {
    icon: "vhs",
    filenames: ["tape"],
  },
  {
    icon: "video",
    filenames: [
      "webm",
      "mkv",
      "flv",
      "vob",
      "ogv",
      "ogg",
      "gifv",
      "avi",
      "mov",
      "qt",
      "wmv",
      "yuv",
      "rm",
      "rmvb",
      "mp4",
      "m4v",
      "mpg",
      "mp2",
      "mpeg",
      "mpe",
      "mpv",
      "m2v",
    ],
  },
  {
    icon: "vim",
    filenames: ["vimrc", "gvimrc", "exrc", "vim", "viminfo"],
  },
  {
    icon: "visual_studio",
    filenames: [
      "csproj",
      "ruleset",
      "sln",
      "suo",
      "vb",
      "vbs",
      "vcxitems",
      "vcxitems.filters",
      "vcxproj",
      "vcxproj.filters",
    ],
  },
  {
    icon: "vital",
    filenames: [
      "vital",
      "vitalbank",
      "vitallfo",
      "vitalskin",
      "vitaltable",
      "vitaltheme",
    ],
  },
  {
    icon: "vscode",
    filenames: [
      "vsixmanifest",
      "vsix",
      "code-workplace",
      "code-workspace",
      "code-profile",
      "code-snippets",
    ],
  },
  {
    icon: "vue",
    filenames: ["vue"],
  },
  {
    icon: "web_assembly",
    filenames: ["wat", "wasm"],
  },
  {
    icon: "windi",
    filenames: ["windi"],
  },
  {
    icon: "workflow",
    filenames: ["workflows/yml", "workflows/yaml"],
  },
  {
    icon: "xaml",
    filenames: ["xaml"],
  },
  {
    icon: "xml",
    filenames: [
      "xml",
      "plist",
      "xsd",
      "dtd",
      "xsl",
      "xslt",
      "resx",
      "iml",
      "xquery",
      "tmLanguage",
      "manifest",
      "project",
      "xml.dist",
      "xml.dist.sample",
      "dmn",
      "jrxml",
    ],
  },
  {
    icon: "yaml",
    filenames: ["yml", "yaml"],
  },
  {
    icon: "zap",
    filenames: ["zap"],
  },
  {
    icon: "zig",
    filenames: ["zig"],
  },
];
