import { Icon } from "./types";

export const files: Icon[] = [
  {
    filenames: [".adonisrc.json", "ace"],
    icon: "adonis",
  },
  {
    filenames: [".alexrc", ".alexrc.yaml", ".alexrc.yml", ".alexrc.js"],
    icon: "alex",
  },
  {
    filenames: ["androidmanifest.xml"],
    icon: "android",
  },
  {
    filenames: [
      "angular-cli.json",
      ".angular-cli.json",
      "angular.json",
      "ng-package.json",
    ],
    icon: "angular",
  },
  {
    filenames: [".ansible-lint", "ansible-lint.yml", "ansible-lint.yaml"],
    icon: "ansible_lint",
  },
  {
    filenames: ["apollo.config.js", "apollo.config.ts"],
    icon: "apollo",
  },
  {
    filenames: [".ds_store", "apple-app-site-association"],
    icon: "apple",
  },
  {
    filenames: [
      "astro.config.js",
      "astro.config.mjs",
      "astro.config.cjs",
      "astro.config.ts",
      "astro.config.cts",
      "astro.config.mts",
    ],
    icon: "astro_config",
  },
  {
    filenames: [
      "azure-pipelines.yml",
      "azure-pipelines.yaml",
      "azure-pipelines-main.yml",
      "azure-pipelines-main.yaml",
    ],
    icon: "azure_pipelines",
  },
  {
    filenames: [
      ".babelrc",
      ".babelrc.cjs",
      ".babelrc.js",
      ".babelrc.mjs",
      ".babelrc.json",
      "babel.config.cjs",
      "babel.config.js",
      "babel.config.mjs",
      "babel.config.json",
      "babel-transform.js",
      ".babel-plugin-macrosrc",
      ".babel-plugin-macrosrc.json",
      ".babel-plugin-macrosrc.yaml",
      ".babel-plugin-macrosrc.yml",
      ".babel-plugin-macrosrc.js",
      "babel-plugin-macros.config.js",
    ],
    icon: "babel",
  },
  {
    filenames: [
      "applypatch-msg",
      "pre-applypatch",
      "post-applypatch",
      "pre-commit",
      "prepare-commit-message",
      "commit-msg",
      "post-commit",
      "pre-rebase",
      "post-checkout",
      "post-merge",
      "pre-receive",
      "update",
      "post-receive",
      "post-update",
      "pre-auto-gc",
      "post-rewrite",
      "pre-push",
    ],
    icon: "bash",
  },
  {
    filenames: [".bazelrc"],
    icon: "bazel",
  },
  {
    filenames: ["biome.json", "biome.jsonc"],
    icon: "biome",
  },
  {
    filenames: ["bitbucket-pipelines.yaml", "bitbucket-pipelines.yml"],
    icon: "bitbucket",
  },
  {
    filenames: [
      "blitz.config.js",
      "blitz.config.ts",
      ".blitz.config.compiled.js",
    ],
    icon: "blitz",
  },
  {
    filenames: [".bowerrc", "bower.json"],
    icon: "bower",
  },
  {
    filenames: ["browserslist", ".browserslistrc"],
    icon: "browserslist",
  },
  {
    filenames: ["bunfig.toml", "bun.lockb"],
    icon: "bun",
  },
  {
    filenames: ["caddyfile"],
    icon: "caddy",
  },
  {
    filenames: ["capacitor.config.json", "capacitor.config.ts"],
    icon: "capacitor",
  },
  {
    filenames: ["cargo.toml", "cargo.lock"],
    icon: "cargo",
  },
  {
    filenames: [
      "changelog",
      "changelog.md",
      "changelog.rst",
      "changelog.txt",
      "changes",
      "changes.md",
      "changes.rst",
      "changes.txt",
    ],
    icon: "changelog",
  },
  {
    filenames: ["circle.yml"],
    icon: "circle_ci",
  },
  {
    filenames: ["cmakelists.txt", "cmakecache.txt"],
    icon: "cmake",
  },
  {
    filenames: [".codeclimate.yml"],
    icon: "code_climate",
  },
  {
    filenames: ["code_of_conduct.md", "code_of_conduct.txt", "code_of_conduct"],
    icon: "code_of_conduct",
  },
  {
    filenames: ["codeowners", "owners"],
    icon: "codeowners",
  },
  {
    filenames: [
      ".commitlintrc",
      ".commitlintrc.js",
      ".commitlintrc.cjs",
      ".commitlintrc.ts",
      ".commitlintrc.cts",
      ".commitlintrc.json",
      ".commitlintrc.yaml",
      ".commitlintrc.yml",
      ".commitlint.yaml",
      ".commitlint.yml",
      "commitlint.config.js",
      "commitlint.config.cjs",
      "commitlint.config.ts",
      "commitlint.config.cts",
    ],
    icon: "commitlint",
  },
  {
    filenames: [
      "contributing.md",
      "contributing.rst",
      "contributing.txt",
      "contributing",
    ],
    icon: "contributing",
  },
  {
    filenames: [
      "cspell.json",
      "cspell.yml",
      "cspell.yaml",
      ".cspell.json",
      ".cspell.yml",
      ".cspell.yaml",
      "cspell.config.js",
      "cspell.config.cjs",
      "cspell.config.yml",
      "cspell.config.yaml",
    ],
    icon: "cspell",
  },
  {
    filenames: [
      "cypress.json",
      "cypress.env.json",
      "cypress.config.ts",
      "cypress.config.js",
      "cypress.config.cjs",
      "cypress.config.mjs",
    ],
    icon: "cypress",
  },
  {
    filenames: ["deno.json", "deno.jsonc", "deno.lock"],
    icon: "deno",
  },
  {
    filenames: ["dependabot.yml", "dependabot.yaml"],
    icon: "dependabot",
  },
  {
    filenames: ["devcontainer.json", ".devcontainer.json"],
    icon: "devcontainer",
  },
  {
    filenames: [
      "dockerfile",
      "dockerfile.prod",
      "dockerfile.production",
      "dockerfile.alpha",
      "dockerfile.beta",
      "dockerfile.stage",
      "dockerfile.staging",
      "dockerfile.dev",
      "dockerfile.development",
      "dockerfile.local",
      "dockerfile.test",
      "dockerfile.testing",
      "dockerfile.ci",
      "dockerfile.web",
      "dockerfile.worker",
      "containerfile",
      "containerfile.prod",
      "containerfile.production",
      "containerfile.alpha",
      "containerfile.beta",
      "containerfile.stage",
      "containerfile.staging",
      "containerfile.dev",
      "containerfile.development",
      "containerfile.local",
      "containerfile.test",
      "containerfile.testing",
      "containerfile.ci",
      "containerfile.web",
      "containerfile.worker",
    ],
    icon: "docker",
  },
  {
    filenames: [
      "docker-compose.yml",
      "docker-compose.override.yml",
      "docker-compose.prod.yml",
      "docker-compose.production.yml",
      "docker-compose.alpha.yml",
      "docker-compose.beta.yml",
      "docker-compose.stage.yml",
      "docker-compose.staging.yml",
      "docker-compose.dev.yml",
      "docker-compose.development.yml",
      "docker-compose.local.yml",
      "docker-compose.test.yml",
      "docker-compose.testing.yml",
      "docker-compose.ci.yml",
      "docker-compose.web.yml",
      "docker-compose.worker.yml",
      "docker-compose.yaml",
      "docker-compose.override.yaml",
      "docker-compose.prod.yaml",
      "docker-compose.production.yaml",
      "docker-compose.alpha.yaml",
      "docker-compose.beta.yaml",
      "docker-compose.stage.yaml",
      "docker-compose.staging.yaml",
      "docker-compose.dev.yaml",
      "docker-compose.development.yaml",
      "docker-compose.local.yaml",
      "docker-compose.test.yaml",
      "docker-compose.testing.yaml",
      "docker-compose.ci.yaml",
      "docker-compose.web.yaml",
      "docker-compose.worker.yaml",
      "compose.yaml",
      "compose.override.yaml",
      "compose.prod.yaml",
      "compose.production.yaml",
      "compose.alpha.yaml",
      "compose.beta.yaml",
      "compose.stage.yaml",
      "compose.staging.yaml",
      "compose.dev.yaml",
      "compose.development.yaml",
      "compose.local.yaml",
      "compose.test.yaml",
      "compose.testing.yaml",
      "compose.ci.yaml",
      "compose.web.yaml",
      "compose.worker.yaml",
      "compose.yml",
      "compose.override.yml",
      "compose.prod.yml",
      "compose.production.yml",
      "compose.alpha.yml",
      "compose.beta.yml",
      "compose.stage.yml",
      "compose.staging.yml",
      "compose.dev.yml",
      "compose.development.yml",
      "compose.local.yml",
      "compose.test.yml",
      "compose.testing.yml",
      "compose.ci.yml",
      "compose.web.yml",
      "compose.worker.yml",
    ],
    icon: "docker_compose",
  },
  {
    filenames: ["dub.json", "dub.sdl", "dub.selections.json"],
    icon: "dub",
  },
  {
    filenames: [".editorconfig"],
    icon: "editorconfig",
  },
  {
    filenames: [
      ".eleventy.js",
      "eleventy.config.js",
      "eleventy.config.mjs",
      "eleventy.config.cjs",
      ".eleventyignore",
    ],
    icon: "eleventy",
  },
  {
    filenames: [".ember-cli", ".ember-cli.js", "ember-cli-builds.js"],
    icon: "ember",
  },
  {
    filenames: [
      ".env.defaults",
      ".env.example",
      ".env.sample",
      ".env.template",
      ".env.schema",
      ".env.local",
      ".env.dev",
      ".env.development",
      ".env.alpha",
      ".env.e2e",
      ".env.qa",
      ".env.dist",
      ".env.prod",
      ".env.production",
      ".env.stage",
      ".env.staging",
      ".env.preview",
      ".env.test",
      ".env.testing",
      ".env.development.local",
      ".env.qa.local",
      ".env.production.local",
      ".env.staging.local",
      ".env.test.local",
      ".env.uat",
      ".env.cat",
    ],
    icon: "env",
  },
  {
    filenames: [
      "esbuild.js",
      "esbuild.ts",
      "esbuild.cjs",
      "esbuild.mjs",
      "esbuild.config.js",
      "esbuild.config.ts",
      "esbuild.config.cjs",
      "esbuild.config.mjs",
    ],
    icon: "esbuild",
  },
  {
    filenames: [
      ".eslintrc.js",
      ".eslintrc.cjs",
      ".eslintrc.yaml",
      ".eslintrc.yml",
      ".eslintrc.json",
      ".eslintrc-md.js",
      ".eslintrc-jsdoc.js",
      ".eslintrc",
      "eslint.config.js",
      "eslint.config.cjs",
      "eslint.config.mjs",
      "eslint.config.ts",
      ".eslintignore",
      ".eslintcache",
    ],
    icon: "eslint",
  },
  {
    filenames: ["fastfile", "appfile"],
    icon: "fastlane",
  },
  {
    filenames: ["favicon.ico"],
    icon: "favicon",
  },
  {
    filenames: [
      "firebase.json",
      ".firebaserc",
      "firestore.rules",
      "firestore.indexes.json",
    ],
    icon: "firebase",
  },
  {
    filenames: [
      "gatsby-config.js",
      "gatsby-config.mjs",
      "gatsby-config.ts",
      "gatsby-node.js",
      "gatsby-node.mjs",
      "gatsby-node.ts",
      "gatsby-browser.js",
      "gatsby-browser.tsx",
      "gatsby-ssr.js",
      "gatsby-ssr.tsx",
    ],
    icon: "gatsby",
  },
  {
    filenames: ["release-please-config.json", ".release-please-manifest.json"],
    icon: "gcp",
  },
  {
    filenames: [
      ".git",
      ".gitignore",
      ".gitmessage",
      ".gitignore-global",
      ".gitignore_global",
      ".gitattributes",
      ".gitattributes-global",
      ".gitattributes_global",
      ".gitconfig",
      ".gitmodules",
      ".gitkeep",
      ".keep",
      ".gitpreserve",
      ".gitinclude",
      ".git-blame-ignore",
      ".git-blame-ignore-revs",
      ".git-for-windows-updater",
      "git-history",
    ],
    icon: "git",
  },
  {
    filenames: ["cliff.toml"],
    icon: "git_cliff",
  },
  {
    filenames: [".gitpod.yml"],
    icon: "gitpod",
  },
  {
    filenames: ["gleam.toml"],
    icon: "gleam_config",
  },
  {
    filenames: ["go.mod", "go.sum", "go.work", "go.work.sum"],
    icon: "go_mod",
  },
  {
    filenames: [".gdignore", "._sc_", "_sc_"],
    icon: "godot_assets",
  },
  {
    filenames: ["gradle.properties", "gradlew", "gradle-wrapper.properties"],
    icon: "gradle",
  },
  {
    filenames: [
      ".graphqlconfig",
      ".graphqlrc",
      ".graphqlrc.json",
      ".graphqlrc.js",
      ".graphqlrc.cjs",
      ".graphqlrc.ts",
      ".graphqlrc.toml",
      ".graphqlrc.yaml",
      ".graphqlrc.yml",
      "graphql.config.json",
      "graphql.config.js",
      "graphql.config.cjs",
      "graphql.config.ts",
      "graphql.config.toml",
      "graphql.config.yaml",
      "graphql.config.yml",
    ],
    icon: "graphql",
  },
  {
    filenames: [
      "gulpfile.js",
      "gulpfile.mjs",
      "gulpfile.ts",
      "gulpfile.cts",
      "gulpfile.mts",
      "gulpfile.babel.js",
    ],
    icon: "gulp",
  },
  {
    filenames: [".helmignore", "chart.lock"],
    icon: "helm",
  },
  {
    filenames: ["procfile"],
    icon: "heroku",
  },
  {
    filenames: [
      "histoire.config.ts",
      "histoire.config.js",
      ".histoire.js",
      ".histoire.ts",
    ],
    icon: "histoire",
  },
  {
    filenames: [
      ".huskyrc",
      "husky.config.js",
      ".huskyrc.json",
      ".huskyrc.js",
      ".huskyrc.yaml",
      ".huskyrc.yml",
    ],
    icon: "husky",
  },
  {
    filenames: ["ionic.config.json", ".io-config.json"],
    icon: "ionic",
  },
  {
    filenames: ["jsconfig.json"],
    icon: "javascript",
  },
  {
    filenames: [
      "jest.config.js",
      "jest.config.cjs",
      "jest.config.mjs",
      "jest.config.ts",
      "jest.config.cts",
      "jest.config.mts",
      "jest.config.json",
      "jest.e2e.config.js",
      "jest.e2e.config.cjs",
      "jest.e2e.config.mjs",
      "jest.e2e.config.ts",
      "jest.e2e.config.cts",
      "jest.e2e.config.mts",
      "jest.e2e.config.json",
      "jest.e2e.json",
      "jest-unit.config.js",
      "jest-e2e.config.js",
      "jest-e2e.config.cjs",
      "jest-e2e.config.mjs",
      "jest-e2e.config.ts",
      "jest-e2e.config.cts",
      "jest-e2e.config.mts",
      "jest-e2e.config.json",
      "jest-e2e.json",
      "jest-github-actions-reporter.js",
      "jest.setup.js",
      "jest.setup.ts",
      "jest.json",
      ".jestrc",
      ".jestrc.js",
      ".jestrc.json",
      "jest.teardown.js",
      "jest-preset.json",
      "jest-preset.js",
      "jest-preset.cjs",
      "jest-preset.mjs",
      "jest.preset.js",
      "jest.preset.mjs",
      "jest.preset.cjs",
      "jest.preset.json",
    ],
    icon: "jest",
  },
  {
    filenames: [
      ".lintstagedrc",
      ".lintstagedrc.json",
      ".lintstagedrc.yaml",
      ".lintstagedrc.yml",
      ".lintstagedrc.mjs",
      ".lintstagedrc.cjs",
      ".lintstagedrc.js",
      "lint-staged.config.js",
      "lint-staged.config.mjs",
      "lint-staged.config.cjs",
    ],
    icon: "lint_staged",
  },
  {
    filenames: ["justfile"],
    icon: "just",
  },
  {
    filenames: [".htpasswd", "maven.config", "jvm.config", "pom.xml"],
    icon: "apache",
  },
  {
    filenames: ["artisan"],
    icon: "laravel",
  },
  {
    filenames: ["lerna.json"],
    icon: "lerna",
  },
  {
    filenames: [
      "copying",
      "copying.md",
      "copying.rst",
      "copying.txt",
      "copyright",
      "copyright.md",
      "copyright.rst",
      "copyright.txt",
      "license",
      "license-agpl",
      "license-apache",
      "license-bsd",
      "license-mit",
      "license-gpl",
      "license-lgpl",
      "license.md",
      "license.rst",
      "license.txt",
      "licence",
      "licence-agpl",
      "licence-apache",
      "licence-bsd",
      "licence-mit",
      "licence-gpl",
      "licence-lgpl",
      "licence.md",
      "licence.rst",
      "licence.txt",
    ],
    icon: "license",
  },
  {
    filenames: [".modernizrrc", ".modernizrrc.js", ".modernizrrc.json"],
    icon: "modernizr",
  },
  {
    filenames: ["nativescript.config.ts", "nativescript.config.js"],
    icon: "nativescript",
  },
  {
    filenames: [
      "nest-cli.json",
      ".nest-cli.json",
      "nestconfig.json",
      ".nestconfig.json",
    ],
    icon: "nest",
  },
  {
    filenames: ["netlify.json", "netlify.yml", "netlify.yaml", "netlify.toml"],
    icon: "netlify",
  },
  {
    filenames: [
      "next.config.js",
      "next.config.mjs",
      "next.config.ts",
      "next.config.mts",
    ],
    icon: "next",
  },
  {
    filenames: ["nginx.conf"],
    icon: "nginx",
  },
  {
    filenames: ["nodemon.json", "nodemon-debug.json"],
    icon: "nodemon",
  },
  {
    filenames: [
      ".npmrc",
      ".npmignore",
      "package-lock.json",
      "package.json",
      ".nvmrc",
      ".esmrc",
      ".node-version",
    ],
    icon: "npm",
  },
  {
    filenames: ["nuget.config", ".nuspec", "nuget.exe"],
    icon: "nuget",
  },
  {
    filenames: [".nuxtrc", "nuxt.config.js", "nuxt.config.ts", ".nuxtignore"],
    icon: "nuxt",
  },
  {
    filenames: [
      "panda.config.ts",
      "panda.config.js",
      "panda.config.mjs",
      "panda.config.mts",
      "panda.config.cjs",
    ],
    icon: "panda_css",
  },
  {
    filenames: [
      ".phrase.yml",
      ".phraseapp.yml",
      ".phrase.yaml",
      ".phraseapp.yaml",
    ],
    icon: "phrase",
  },
  {
    filenames: ["pixi.toml", "pixi.lock"],
    icon: "pixi",
  },
  {
    filenames: [
      "playwright.config.js",
      "playwright.config.mjs",
      "playwright.config.ts",
      "playwright.config.base.js",
      "playwright.config.base.mjs",
      "playwright.config.base.ts",
      "playwright-ct.config.js",
      "playwright-ct.config.mjs",
      "playwright-ct.config.ts",
    ],
    icon: "playwright",
  },
  {
    filenames: ["pnpm-workspace.yaml", ".pnpmfile.cjs", "pnpm-lock.yaml"],
    icon: "pnpm",
  },
  {
    filenames: [
      "postcss.config.js",
      "postcss.config.cjs",
      "postcss.config.ts",
      "postcss.config.cts",
      ".postcssrc.js",
      ".postcssrc.cjs",
      ".postcssrc.ts",
      ".postcssrc.cts",
      ".postcssrc",
      ".postcssrc.json",
      ".postcssrc.yaml",
      ".postcssrc.yml",
    ],
    icon: "postcss",
  },
  {
    filenames: [
      ".prettierrc",
      "prettier.config.js",
      "prettier.config.cjs",
      ".prettierrc.js",
      ".prettierrc.cjs",
      ".prettierrc.json",
      ".prettierrc.json5",
      ".prettierrc.yaml",
      ".prettierrc.yml",
      ".prettierrc.toml",
      "prettier.config.mjs",
      ".prettierrc.mjs",
      ".prettierignore",
    ],
    icon: "prettier",
  },
  {
    filenames: ["prisma.yml"],
    icon: "prisma",
  },
  {
    filenames: [".pug-lintrc", ".pug-lintrc.js", ".pug-lintrc.json"],
    icon: "pug",
  },
  {
    filenames: [
      ".puppeteerrc.cjs",
      ".puppeteerrc.js",
      ".puppeteerrc.json",
      ".puppeteerrc.yaml",
      ".puppeteerrc",
      "puppeteer.config.js",
      "puppeteer.config.cjs",
    ],
    icon: "puppeteer",
  },
  {
    filenames: ["redwood.toml"],
    icon: "redwood",
  },
  {
    filenames: ["remix.config.js", "remix.config.ts"],
    icon: "remix",
  },
  {
    filenames: [
      "rollup.config.js",
      "rollup.config.mjs",
      "rollup.config.ts",
      "rollup-config.js",
      "rollup-config.mjs",
      "rollup-config.ts",
      "rollup.config.common.js",
      "rollup.config.common.mjs",
      "rollup.config.common.ts",
      "rollup.config.base.js",
      "rollup.config.base.mjs",
      "rollup.config.base.ts",
      "rollup.config.prod.js",
      "rollup.config.prod.mjs",
      "rollup.config.prod.ts",
      "rollup.config.dev.js",
      "rollup.config.dev.mjs",
      "rollup.config.dev.ts",
      "rollup.config.prod.vendor.js",
      "rollup.config.prod.vendor.mjs",
      "rollup.config.prod.vendor.ts",
    ],
    icon: "rollup",
  },
  {
    filenames: [".ruby-version", "gemfile", "gemfile.lock"],
    icon: "ruby",
  },
  {
    filenames: ["ruff.toml", ".ruff.toml"],
    icon: "ruff",
  },
  {
    filenames: ["semgrep.yml", ".semgrepignore"],
    icon: "semgrep",
  },
  {
    filenames: [".sentryclirc"],
    icon: "sentry",
  },
  {
    filenames: [
      "serverless.yml",
      "serverless.yaml",
      "serverless.json",
      "serverless.js",
      "serverless.ts",
    ],
    icon: "serverless",
  },
  {
    filenames: [
      "snowpack.config.js",
      "snowpack.config.cjs",
      "snowpack.config.mjs",
      "snowpack.config.ts",
      "snowpack.config.cts",
      "snowpack.config.mts",
      "snowpack.deps.json",
      "snowpack.config.json",
    ],
    icon: "snowpack",
  },
  {
    filenames: [
      "sonar-project.properties",
      ".sonarcloud.properties",
      "sonarcloud.yaml",
    ],
    icon: "sonar_cloud",
  },
  {
    filenames: [".stackblitzrc"],
    icon: "stackblitz",
  },
  {
    filenames: [
      ".stylelintrc",
      "stylelint.config.js",
      "stylelint.config.cjs",
      "stylelint.config.mjs",
      ".stylelintrc.json",
      ".stylelintrc.yaml",
      ".stylelintrc.yml",
      ".stylelintrc.js",
      ".stylelintrc.cjs",
      ".stylelintrc.mjs",
      ".stylelintignore",
      ".stylelintcache",
    ],
    icon: "stylelint",
  },
  {
    filenames: [
      "svelte.config.js",
      "svelte.config.ts",
      "svelte.config.cjs",
      "svelte.config.mjs",
    ],
    icon: "svelte_config",
  },
  {
    filenames: [
      "tailwind.js",
      "tailwind.ts",
      "tailwind.config.js",
      "tailwind.config.cjs",
      "tailwind.config.mjs",
      "tailwind.config.ts",
      "tailwind.config.cts",
      "tailwind.config.mts",
    ],
    icon: "tailwind",
  },
  {
    filenames: [
      "tauri.conf.json",
      "tauri.config.json",
      "tauri.linux.conf.json",
      "tauri.windows.conf.json",
      "tauri.macos.conf.json",
      ".taurignore",
    ],
    icon: "tauri",
  },
  {
    filenames: ["turbo.json"],
    icon: "turbo",
  },
  {
    filenames: [
      "tsconfig.json",
      "tsconfig.app.json",
      "tsconfig.editor.json",
      "tsconfig.spec.json",
      "tsconfig.base.json",
      "tsconfig.build.json",
      "tsconfig.eslint.json",
      "tsconfig.lib.json",
      "tsconfig.lib.prod.json",
      "tsconfig.node.json",
      "tsconfig.test.json",
      "tsconfig.e2e.json",
      "tsconfig.web.json",
      "tsconfig.webworker.json",
      "tsconfig.worker.json",
      "tsconfig.config.json",
      "tsconfig.vitest.json",
      "tsconfig.cjs.json",
      "tsconfig.esm.json",
      "tsconfig.mjs.json",
      "tsconfig.doc.json",
      "tsconfig.paths.json",
      "tsconfig.main.json",
      "tsconfig.cypress-ct.json",
      "tsconfig.components.json",
    ],
    icon: "typescript",
  },
  {
    filenames: [
      "uno.config.js",
      "uno.config.mjs",
      "uno.config.ts",
      "uno.config.mts",
      "unocss.config.js",
      "unocss.config.mjs",
      "unocss.config.ts",
      "unocss.config.mts",
    ],
    icon: "unocss",
  },
  {
    filenames: ["vercel.json", "now.json", ".vercelignore", ".nowignore"],
    icon: "vercel",
  },
  {
    filenames: [
      "vite.config.js",
      "vite.config.mjs",
      "vite.config.cjs",
      "vite.config.ts",
      "vite.config.cts",
      "vite.config.mts",
    ],
    icon: "vite",
  },
  {
    filenames: [
      "vitest.config.ts",
      "vitest.config.mts",
      "vitest.config.cts",
      "vitest.config.js",
      "vitest.config.mjs",
      "vitest.config.cjs",
    ],
    icon: "vitest",
  },
  {
    filenames: [".vscodeignore"],
    icon: "vscode_ignore",
  },
  {
    filenames: ["vue.config.js", "vue.config.ts"],
    icon: "vue",
  },
  {
    filenames: [
      "webpack.js",
      "webpack.cjs",
      "webpack.mjs",
      "webpack.ts",
      "webpack.cts",
      "webpack.mts",
      "webpack.base.js",
      "webpack.base.cjs",
      "webpack.base.mjs",
      "webpack.base.ts",
      "webpack.base.cts",
      "webpack.base.mts",
      "webpack.config.js",
      "webpack.config.cjs",
      "webpack.config.mjs",
      "webpack.config.ts",
      "webpack.config.cts",
      "webpack.config.mts",
      "webpack.common.js",
      "webpack.common.cjs",
      "webpack.common.mjs",
      "webpack.common.ts",
      "webpack.common.cts",
      "webpack.common.mts",
      "webpack.config.common.js",
      "webpack.config.common.cjs",
      "webpack.config.common.mjs",
      "webpack.config.common.ts",
      "webpack.config.common.cts",
      "webpack.config.common.mts",
      "webpack.config.common.babel.js",
      "webpack.config.common.babel.ts",
      "webpack.dev.js",
      "webpack.dev.cjs",
      "webpack.dev.mjs",
      "webpack.dev.ts",
      "webpack.dev.cts",
      "webpack.dev.mts",
      "webpack.development.js",
      "webpack.development.cjs",
      "webpack.development.mjs",
      "webpack.development.ts",
      "webpack.development.cts",
      "webpack.development.mts",
      "webpack.config.dev.js",
      "webpack.config.dev.cjs",
      "webpack.config.dev.mjs",
      "webpack.config.dev.ts",
      "webpack.config.dev.cts",
      "webpack.config.dev.mts",
      "webpack.config.dev.babel.js",
      "webpack.config.dev.babel.ts",
      "webpack.config.main.js",
      "webpack.config.renderer.ts",
      "webpack.mix.js",
      "webpack.mix.cjs",
      "webpack.mix.mjs",
      "webpack.mix.ts",
      "webpack.mix.cts",
      "webpack.mix.mts",
      "webpack.prod.js",
      "webpack.prod.cjs",
      "webpack.prod.mjs",
      "webpack.prod.ts",
      "webpack.prod.cts",
      "webpack.prod.mts",
      "webpack.prod.config.js",
      "webpack.prod.config.cjs",
      "webpack.prod.config.mjs",
      "webpack.prod.config.ts",
      "webpack.prod.config.cts",
      "webpack.prod.config.mts",
      "webpack.production.js",
      "webpack.production.cjs",
      "webpack.production.mjs",
      "webpack.production.ts",
      "webpack.production.cts",
      "webpack.production.mts",
      "webpack.server.js",
      "webpack.server.cjs",
      "webpack.server.mjs",
      "webpack.server.ts",
      "webpack.server.cts",
      "webpack.server.mts",
      "webpack.client.js",
      "webpack.client.cjs",
      "webpack.client.mjs",
      "webpack.client.ts",
      "webpack.client.cts",
      "webpack.client.mts",
      "webpack.config.server.js",
      "webpack.config.server.cjs",
      "webpack.config.server.mjs",
      "webpack.config.server.ts",
      "webpack.config.server.cts",
      "webpack.config.server.mts",
      "webpack.config.client.js",
      "webpack.config.client.cjs",
      "webpack.config.client.mjs",
      "webpack.config.client.ts",
      "webpack.config.client.cts",
      "webpack.config.client.mts",
      "webpack.config.production.babel.js",
      "webpack.config.production.babel.ts",
      "webpack.config.prod.babel.js",
      "webpack.config.prod.babel.cjs",
      "webpack.config.prod.babel.mjs",
      "webpack.config.prod.babel.ts",
      "webpack.config.prod.babel.cts",
      "webpack.config.prod.babel.mts",
      "webpack.config.prod.js",
      "webpack.config.prod.cjs",
      "webpack.config.prod.mjs",
      "webpack.config.prod.ts",
      "webpack.config.prod.cts",
      "webpack.config.prod.mts",
      "webpack.config.production.js",
      "webpack.config.production.cjs",
      "webpack.config.production.mjs",
      "webpack.config.production.ts",
      "webpack.config.production.cts",
      "webpack.config.production.mts",
      "webpack.config.staging.js",
      "webpack.config.staging.cjs",
      "webpack.config.staging.mjs",
      "webpack.config.staging.ts",
      "webpack.config.staging.cts",
      "webpack.config.staging.mts",
      "webpack.config.babel.js",
      "webpack.config.babel.ts",
      "webpack.config.base.babel.js",
      "webpack.config.base.babel.ts",
      "webpack.config.base.js",
      "webpack.config.base.cjs",
      "webpack.config.base.mjs",
      "webpack.config.base.ts",
      "webpack.config.base.cts",
      "webpack.config.base.mts",
      "webpack.config.staging.babel.js",
      "webpack.config.staging.babel.ts",
      "webpack.config.coffee",
      "webpack.config.test.js",
      "webpack.config.test.cjs",
      "webpack.config.test.mjs",
      "webpack.config.test.ts",
      "webpack.config.test.cts",
      "webpack.config.test.mts",
      "webpack.config.vendor.js",
      "webpack.config.vendor.cjs",
      "webpack.config.vendor.mjs",
      "webpack.config.vendor.ts",
      "webpack.config.vendor.cts",
      "webpack.config.vendor.mts",
      "webpack.config.vendor.production.js",
      "webpack.config.vendor.production.cjs",
      "webpack.config.vendor.production.mjs",
      "webpack.config.vendor.production.ts",
      "webpack.config.vendor.production.cts",
      "webpack.config.vendor.production.mts",
      "webpack.test.js",
      "webpack.test.cjs",
      "webpack.test.mjs",
      "webpack.test.ts",
      "webpack.test.cts",
      "webpack.test.mts",
      "webpack.dist.js",
      "webpack.dist.cjs",
      "webpack.dist.mjs",
      "webpack.dist.ts",
      "webpack.dist.cts",
      "webpack.dist.mts",
      "webpackfile.js",
      "webpackfile.cjs",
      "webpackfile.mjs",
      "webpackfile.ts",
      "webpackfile.cts",
      "webpackfile.mts",
    ],
    icon: "webpack",
  },
  {
    filenames: [
      "windi.config.js",
      "windi.config.cjs",
      "windi.config.ts",
      "windi.config.cts",
      "windi.config.json",
    ],
    icon: "windi",
  },
  {
    filenames: ["wxt.config.js", "wxt.config.ts"],
    icon: "wxt",
  },
  {
    filenames: [
      ".yarnrc",
      ".yarnclean",
      ".yarn-integrity",
      "yarn-error.log",
      ".yarnrc.yml",
      ".yarnrc.yaml",
      "yarn.config.cjs",
      "yarn.lock",
    ],
    icon: "yarn",
  },
];
