import { Icon } from "./types";

export const folders: Icon[] = [
  {
    icon: "src",
    filenames: [
      "source",
      "sources",
      "src",
      "project",
      "projects",
      "app",
      "apps",
      "code",
    ],
  },
  { icon: "devcontainer", filenames: [".devcontainer", "devcontainer"] },
  { icon: "github", filenames: ["github", ".github", "workflow", "workflows"] },
  { icon: "husky", filenames: ["husky", ".husky"] },
  {
    icon: "git",
    filenames: [
      "git",
      ".git",
      "patches",
      "githooks",
      ".githooks",
      "submodules",
      ".submodules",
    ],
  },
  { icon: "idea", filenames: [".idea", "idea"] },
  { icon: "angular", filenames: [".angular", "angular"] },
  { icon: "vscode", filenames: ["vscode", ".vscode"] },
  { icon: "nx", filenames: ["nx", ".nx"] },
  { icon: "hole", filenames: ["node_modules"] },
  {
    icon: "component",
    filenames: ["component", "components"],
  },
  {
    icon: "typescript",
    filenames: [
      "type",
      "types",
      "model",
      "models",
      "interface",
      "interfaces",
      "typings",
      "@types",
    ],
  },
  {
    icon: "util",
    filenames: ["utils", "util", "utility", "utilities"],
  },
  {
    icon: "constant",
    filenames: ["constant", "constants"],
  },
  {
    icon: "test",
    filenames: [
      "test",
      "tests",
      "e2e",
      "integration",
      "integrations",
      "coverage",
      ".nvc-output",
      "it",
      "integration-test",
      "integration-tests",
      "__integration-test__",
      "__integration-tests__",
      "testing",
      "__tests__",
      "__test__",
      "spec",
      "specs",
    ],
  },
  { icon: "style", filenames: ["style", "styles"] },
  { icon: "android", filenames: ["android"] },
  { icon: "ios", filenames: ["ios"] },
  {
    icon: "assets",
    filenames: [
      "asset",
      "assets",
      "public",
      "image",
      "images",
      "_images",
      "_image",
      "_imgs",
      "_img",
      "imgs",
      "img",
      "icons",
      "icon",
      "ico",
      "figures",
      "figure",
      "figs",
      "fig",
      "screenshot",
      "screenshots",
      "screengrab",
      "screengrabs",
      "pic",
      "pics",
      "picture",
      "pictures",
      "photo",
      "photos",
      "photograph",
      "photographs",
    ],
  },
  {
    icon: "cypress",
    filenames: ["cypress", ".cypress"],
  },
  {
    icon: "playwright",
    filenames: ["playwright"],
  },
  {
    icon: "locale",
    filenames: [
      "i18n",
      "internationalization",
      "lang",
      "langs",
      "language",
      "languages",
      "locale",
      "locales",
      "i10n",
      "localization",
      "translation",
      "translate",
      "translations",
      ".tx",
    ],
  },
  {
    icon: "draft",
    filenames: [
      "_draft",
      "_drafts",
      "fixture",
      "fixtures",
      "mocks",
      "mock",
      "concept",
      "concepts",
      "sketch",
      "sketches",
    ],
  },
  {
    icon: "dist",
    filenames: ["dist", "out", "build", "release", ".output", "bin"],
  },
  {
    icon: "view",
    filenames: [
      "view",
      "views",
      "screen",
      "screens",
      "page",
      "pages",
      "public_html",
      "html",
    ],
  },
  { icon: "convex", filenames: ["convex"] },
  {
    icon: "audio",
    filenames: ["aud", "auds", "audio", "audios", "music", "sound", "sounds"],
  },
  { icon: "aws", filenames: ["aws", ".aws"] },
  {
    icon: "azure",
    filenames: [".azure-devops", ".azuredevops", ".azure-pipelines"],
  },
  {
    icon: "benchmark",
    filenames: [
      "benchmark",
      "benchmarks",
      "performance",
      "measure",
      "measures",
      "measurement",
    ],
  },
  {
    icon: "caddy",
    filenames: ["caddy", ".caddy", "caddyfiles", ".caddyfiles"],
  },
  { icon: "pwa", filenames: ["pwa"] },
  { icon: "cloud", filenames: ["cloud"] },
  {
    icon: "command",
    filenames: ["command", "commands", "cli", "clis", "cmd"],
  },
  {
    icon: "config",
    filenames: [
      "cfg",
      "cfgs",
      "conf",
      ".config",
      "config",
      "configs",
      "configuration",
      "configurations",
      "setting",
      ".setting",
      "settings",
      ".settings",
      "META-INF",
      "options",
      "option",
    ],
  },
  {
    icon: "connection",
    filenames: ["connection", "connections"],
  },
  {
    icon: "db",
    filenames: ["db", "database", "databases", "sql", "data", "_data"],
  },
  {
    icon: "debug",
    filenames: ["debug", "debugging"],
  },
  {
    icon: "docker",
    filenames: ["docker", ".docker", "dockerfiles"],
  },
  {
    icon: "docs",
    filenames: [
      "_post",
      "_posts",
      "doc",
      "docs",
      "document",
      "documents",
      "documentation",
      "post",
      "posts",
      "article",
      "articles",
    ],
  },
  {
    icon: "download",
    filenames: ["downloads", "download"],
  },
  {
    icon: "fastlane",
    filenames: ["fastlane", ".fastlane"],
  },
  {
    icon: "firebase",
    filenames: ["firebase", ".firebase"],
  },
  { icon: "font", filenames: ["font", "fonts"] },
  {
    icon: "function",
    filenames: [
      "func",
      "funcs",
      "functions",
      "function",
      "lambda",
      "lambdas",
      "logic",
      "math",
      "maths",
      "calc",
      "calcs",
      "calculation",
      "calculations",
    ],
  },
  {
    icon: "gitlab",
    filenames: ["gitlab", ".gitlab"],
  },
  {
    icon: "kubernetes",
    filenames: ["kubernetes", ".kubernetes", "k8s", ".k8s"],
  },
  { icon: "next", filenames: [".next"] },
  { icon: "nuxt", filenames: ["nuxt", ".nuxt"] },
  {
    icon: "plugin",
    filenames: [
      "plugin",
      "plugins",
      "_plugins",
      "mod",
      "mods",
      "modding",
      "extension",
      "extensions",
      "addon",
      "addons",
      "module",
      "modules",
    ],
  },
  { icon: "prisma", filenames: ["prisma"] },
  {
    icon: "site",
    filenames: [
      "_site",
      "www",
      "wwwroot",
      "web",
      "website",
      "site",
      "browser",
      "browsers",
    ],
  },
  { icon: "redux", filenames: ["redux"] },
  {
    icon: "route",
    filenames: ["routes", "router", "routers", "route"],
  },
  { icon: "sass", filenames: ["sass", "_sass"] },
  { icon: "scss", filenames: ["scss", "_scss"] },
  { icon: "css", filenames: ["css", "_css"] },
  { icon: "security", filenames: ["security"] },
  {
    icon: "server",
    filenames: ["server", "servers", "backend"],
  },
  {
    icon: "storybook",
    filenames: [".storybook", "storybook", "stories", "__stories__"],
  },
  {
    icon: "tauri",
    filenames: ["tauri", "src-tauri"],
  },
  {
    icon: "cache",
    filenames: ["temp", ".temp", "tmp", ".tmp", "cached", "cache", ".cache"],
  },
  { icon: "turbo", filenames: [".turbo", "turbo"] },
  {
    icon: "upload",
    filenames: ["upload", "uploads"],
  },
  {
    icon: "vercel",
    filenames: [".vercel", "vercel", "now", ".now"],
  },
  {
    icon: "video",
    filenames: ["vid", "vids", "video", "videos", "movie", "movies"],
  },
  { icon: "yarn", filenames: [".yarn"] },
  { icon: "wxt", filenames: [".wxt"] },
  {
    icon: "gradle",
    filenames: ["gradle", ".gradle"],
  },
  {
    icon: "kotlin",
    filenames: ["kotlin", ".kotlin"],
  },
];
